name: Continuous Deployment (CD)

on:
  push:
    branches:
      - feature/get_book_by-id  # Deploy when code is pushed to main

jobs:
  deploy:
    name: Deploy FastAPI
    runs-on: self-hosted  # Runs on your Windows server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Latest Code
        run: |
          git pull origin main

      - name: Restart FastAPI App
        run: |
          taskkill /IM uvicorn.exe /F || echo "Uvicorn not running"
          start cmd /k "cd C:\Users\BLARD\Desktop\fastapi-book-project && venv\Scripts\activate && uvicorn main:app --host 127.0.0.1 --port 8000 --reload"
